//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BTL_LTTQ_QLKhoVLXD.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BTL_LTTQ_QLKhoVLXD.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _lock {
            get {
                object obj = ResourceManager.GetObject("lock", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ▼.
        /// </summary>
        internal static string Character_ArrowDown {
            get {
                return ResourceManager.GetString("Character_ArrowDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ▲.
        /// </summary>
        internal static string Character_ArrowUp {
            get {
                return ResourceManager.GetString("Character_ArrowUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ẩn mật khẩu.
        /// </summary>
        internal static string Checkbox_HidePassword {
            get {
                return ResourceManager.GetString("Checkbox_HidePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hiện mật khẩu.
        /// </summary>
        internal static string Checkbox_ShowPassword {
            get {
                return ResourceManager.GetString("Checkbox_ShowPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xác nhận.
        /// </summary>
        internal static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excel Document(*.xlsx)|*.xlsx.
        /// </summary>
        internal static string FileFilter_Excel {
            get {
                return ResourceManager.GetString("FileFilter_Excel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tạo hóa đơn.
        /// </summary>
        internal static string Form_ButtonCreateReceipt {
            get {
                return ResourceManager.GetString("Form_ButtonCreateReceipt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hóa đơn mới.
        /// </summary>
        internal static string Form_ButtonNewReceipt {
            get {
                return ResourceManager.GetString("Form_ButtonNewReceipt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lưu.
        /// </summary>
        internal static string Form_ButtonSave {
            get {
                return ResourceManager.GetString("Form_ButtonSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm khách hàng mới.
        /// </summary>
        internal static string Form_Text_AddNewCustomer {
            get {
                return ResourceManager.GetString("Form_Text_AddNewCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm nhân viên mới.
        /// </summary>
        internal static string Form_Text_AddNewEmployee {
            get {
                return ResourceManager.GetString("Form_Text_AddNewEmployee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm vật liệu mới.
        /// </summary>
        internal static string Form_Text_AddNewMaterial {
            get {
                return ResourceManager.GetString("Form_Text_AddNewMaterial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm nhà cung cấp mới.
        /// </summary>
        internal static string Form_Text_AddNewSupplier {
            get {
                return ResourceManager.GetString("Form_Text_AddNewSupplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dd-MM-yyyy.
        /// </summary>
        internal static string Format_DateFormat {
            get {
                return ResourceManager.GetString("Format_DateFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tất cả.
        /// </summary>
        internal static string Label_AllOption {
            get {
                return ResourceManager.GetString("Label_AllOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông báo.
        /// </summary>
        internal static string MessageBox_Caption_Notification {
            get {
                return ResourceManager.GetString("MessageBox_Caption_Notification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn có chắc chắn muốn hủy hóa đơn này không?.
        /// </summary>
        internal static string MessageBox_Message_AbortReceipt {
            get {
                return ResourceManager.GetString("MessageBox_Message_AbortReceipt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên đăng nhập đã tồn tại! Vui lòng chọn tên đăng nhập khác.
        /// </summary>
        internal static string MessageBox_Message_AccountExisted {
            get {
                return ResourceManager.GetString("MessageBox_Message_AccountExisted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản {0} không tồn tại!.
        /// </summary>
        internal static string MessageBox_Message_AccountNotExist {
            get {
                return ResourceManager.GetString("MessageBox_Message_AccountNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm thành công!.
        /// </summary>
        internal static string MessageBox_Message_AddEmployeeSuccessfully {
            get {
                return ResourceManager.GetString("MessageBox_Message_AddEmployeeSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm kho {0} thành công!.
        /// </summary>
        internal static string MessageBox_Message_AddWarehouseSuccessfully {
            get {
                return ResourceManager.GetString("MessageBox_Message_AddWarehouseSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn không thể xóa tài khoản của mình!.
        /// </summary>
        internal static string MessageBox_Message_CannotSelfDeleteAccount {
            get {
                return ResourceManager.GetString("MessageBox_Message_CannotSelfDeleteAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không thể đặt lại mật khẩu cho chính mình! Hãy sử dụng chức năng &quot;Thay đổi thông tin cá nhân&quot;.
        /// </summary>
        internal static string MessageBox_Message_CannotSelfResetPassword {
            get {
                return ResourceManager.GetString("MessageBox_Message_CannotSelfResetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không có thay đổi! Thông tin vẫn được giữ nguyên.
        /// </summary>
        internal static string MessageBox_Message_ChangeInfoNoChange {
            get {
                return ResourceManager.GetString("MessageBox_Message_ChangeInfoNoChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thay đổi thành công!.
        /// </summary>
        internal static string MessageBox_Message_ChangeSuccessfully {
            get {
                return ResourceManager.GetString("MessageBox_Message_ChangeSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin của {0} sẽ được thay đổi. Vẫn tiếp tục?.
        /// </summary>
        internal static string MessageBox_Message_ConfirmChangeEmployeeInfo {
            get {
                return ResourceManager.GetString("MessageBox_Message_ConfirmChangeEmployeeInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin của bạn sẽ được thay đổi. Vẫn tiếp tục?.
        /// </summary>
        internal static string MessageBox_Message_ConfirmChangeInfo {
            get {
                return ResourceManager.GetString("MessageBox_Message_ConfirmChangeInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu của bạn sẽ được thay đổi. Vẫn tiếp tục?.
        /// </summary>
        internal static string MessageBox_Message_ConfirmChangePassword {
            get {
                return ResourceManager.GetString("MessageBox_Message_ConfirmChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xác nhận tạo hóa đơn?.
        /// </summary>
        internal static string MessageBox_Message_ConfirmCreateReceipt {
            get {
                return ResourceManager.GetString("MessageBox_Message_ConfirmCreateReceipt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn có chắc chắc muốn xóa các tài khoản sau không?
        ///{0}.
        /// </summary>
        internal static string MessageBox_Message_ConfirmDeleteAccount {
            get {
                return ResourceManager.GetString("MessageBox_Message_ConfirmDeleteAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn có chắc chắc muốn xóa các nhân viên sau không?
        ///{0}.
        /// </summary>
        internal static string MessageBox_Message_ConfirmDeleteEmployee {
            get {
                return ResourceManager.GetString("MessageBox_Message_ConfirmDeleteEmployee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn có chắc chắc muốn xóa khỏi hóa đơn các vật liệu sau không?
        ///{0}.
        /// </summary>
        internal static string MessageBox_Message_ConfirmDeleteItemFromReceipt {
            get {
                return ResourceManager.GetString("MessageBox_Message_ConfirmDeleteItemFromReceipt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn có chắc chắn muốn xóa các vật liệu sau không?
        ///{0}.
        /// </summary>
        internal static string MessageBox_Message_ConfirmDeleteMaterial {
            get {
                return ResourceManager.GetString("MessageBox_Message_ConfirmDeleteMaterial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn có chắc chắn muốn xóa các nhà cung cấp sau không?
        ///{0}.
        /// </summary>
        internal static string MessageBox_Message_ConfirmDeleteSupplier {
            get {
                return ResourceManager.GetString("MessageBox_Message_ConfirmDeleteSupplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn có chắc chắn muốn thoát không?.
        /// </summary>
        internal static string MessageBox_Message_ConfirmExit {
            get {
                return ResourceManager.GetString("MessageBox_Message_ConfirmExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu của tài khoản {0} sẽ được thay đổi. Vẫn tiếp tục?.
        /// </summary>
        internal static string MessageBox_Message_ConfirmResetPassword {
            get {
                return ResourceManager.GetString("MessageBox_Message_ConfirmResetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tạo tài khoản thành công!.
        /// </summary>
        internal static string MessageBox_Message_CreateAccountSuccessfully {
            get {
                return ResourceManager.GetString("MessageBox_Message_CreateAccountSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tạo hóa đơn thành công! Bạn có muốn xuất hóa đơn không?.
        /// </summary>
        internal static string MessageBox_Message_CreateReceiptSuccessfully {
            get {
                return ResourceManager.GetString("MessageBox_Message_CreateReceiptSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã xóa {0} tài khoản!.
        /// </summary>
        internal static string MessageBox_Message_DeleteAccountSuccessfully {
            get {
                return ResourceManager.GetString("MessageBox_Message_DeleteAccountSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã xóa {0} vật liệu!.
        /// </summary>
        internal static string MessageBox_Message_DeleteMaterialSuccessfully {
            get {
                return ResourceManager.GetString("MessageBox_Message_DeleteMaterialSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã xóa {0} nhà cung cấp!.
        /// </summary>
        internal static string MessageBox_Message_DeleteSupplierSuccessfully {
            get {
                return ResourceManager.GetString("MessageBox_Message_DeleteSupplierSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khảu mới không được trùng mật khẩu cũ!.
        /// </summary>
        internal static string MessageBox_Message_DuplicatePassword {
            get {
                return ResourceManager.GetString("MessageBox_Message_DuplicatePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên kho bị trùng! Hãy thử tên khác.
        /// </summary>
        internal static string MessageBox_Message_DuplicateWarehouse {
            get {
                return ResourceManager.GetString("MessageBox_Message_DuplicateWarehouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hãy nhập đầy đủ thông tin tài khoản!.
        /// </summary>
        internal static string MessageBox_Message_EnterFullAccountInfo {
            get {
                return ResourceManager.GetString("MessageBox_Message_EnterFullAccountInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hãy nhập đầy đủ thông tin!.
        /// </summary>
        internal static string MessageBox_Message_EnterFulllInfo {
            get {
                return ResourceManager.GetString("MessageBox_Message_EnterFulllInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hãy nhập mật khẩu mới!.
        /// </summary>
        internal static string MessageBox_Message_EnterNewPassword {
            get {
                return ResourceManager.GetString("MessageBox_Message_EnterNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hãy nhập mật khẩu cũ!.
        /// </summary>
        internal static string MessageBox_Message_EnterOldPassword {
            get {
                return ResourceManager.GetString("MessageBox_Message_EnterOldPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hãy nhập mật khẩu!.
        /// </summary>
        internal static string MessageBox_Message_EnterPassword {
            get {
                return ResourceManager.GetString("MessageBox_Message_EnterPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hãy nhập tên đăng nhập.
        /// </summary>
        internal static string MessageBox_Message_EnterUsername {
            get {
                return ResourceManager.GetString("MessageBox_Message_EnterUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Định dạng họ tên không chính xác! Hãy thử lại.
        /// </summary>
        internal static string MessageBox_Message_InvalidNameFormat {
            get {
                return ResourceManager.GetString("MessageBox_Message_InvalidNameFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Định dạng số điện thoại không chính xác! Hãy thử lại.
        /// </summary>
        internal static string MessageBox_Message_InvalidPhoneNumberFormat {
            get {
                return ResourceManager.GetString("MessageBox_Message_InvalidPhoneNumberFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lỗi hệ thống! Hãy thử lại sau.
        /// </summary>
        internal static string MessageBox_Message_SystemError {
            get {
                return ResourceManager.GetString("MessageBox_Message_SystemError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sai tên tài khoản hoặc mật khẩu!.
        /// </summary>
        internal static string MessageBox_Message_WrongAccountInfo {
            get {
                return ResourceManager.GetString("MessageBox_Message_WrongAccountInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khảu cũ không chính xác!.
        /// </summary>
        internal static string MessageBox_Message_WrongOldPassword {
            get {
                return ResourceManager.GetString("MessageBox_Message_WrongOldPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AddCustomer.
        /// </summary>
        internal static string Permission_AddCustomer {
            get {
                return ResourceManager.GetString("Permission_AddCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AddEmployee.
        /// </summary>
        internal static string Permission_AddEmployee {
            get {
                return ResourceManager.GetString("Permission_AddEmployee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AddMaterial.
        /// </summary>
        internal static string Permission_AddMaterial {
            get {
                return ResourceManager.GetString("Permission_AddMaterial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AddReceipt.
        /// </summary>
        internal static string Permission_AddReceipt {
            get {
                return ResourceManager.GetString("Permission_AddReceipt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AddSupplier.
        /// </summary>
        internal static string Permission_AddSupplier {
            get {
                return ResourceManager.GetString("Permission_AddSupplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CreateAccountEmployee.
        /// </summary>
        internal static string Permission_CreateAccountEmployee {
            get {
                return ResourceManager.GetString("Permission_CreateAccountEmployee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DeleteSupplier.
        /// </summary>
        internal static string Permission_DeleteAccount {
            get {
                return ResourceManager.GetString("Permission_DeleteAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DeleteCustomer.
        /// </summary>
        internal static string Permission_DeleteCustomer {
            get {
                return ResourceManager.GetString("Permission_DeleteCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DeleteEmployee.
        /// </summary>
        internal static string Permission_DeleteEmployee {
            get {
                return ResourceManager.GetString("Permission_DeleteEmployee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DeleteMaterial.
        /// </summary>
        internal static string Permission_DeleteMaterial {
            get {
                return ResourceManager.GetString("Permission_DeleteMaterial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DeleteReceipt.
        /// </summary>
        internal static string Permission_DeleteReceipt {
            get {
                return ResourceManager.GetString("Permission_DeleteReceipt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DeleteSupplier.
        /// </summary>
        internal static string Permission_DeleteSupplier {
            get {
                return ResourceManager.GetString("Permission_DeleteSupplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EditAccountInformation.
        /// </summary>
        internal static string Permission_EditAccountInformation {
            get {
                return ResourceManager.GetString("Permission_EditAccountInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EditCustomer.
        /// </summary>
        internal static string Permission_EditCustomer {
            get {
                return ResourceManager.GetString("Permission_EditCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EditMaterial.
        /// </summary>
        internal static string Permission_EditMaterial {
            get {
                return ResourceManager.GetString("Permission_EditMaterial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EditReceipt.
        /// </summary>
        internal static string Permission_EditReceipt {
            get {
                return ResourceManager.GetString("Permission_EditReceipt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EditSupplierInformation.
        /// </summary>
        internal static string Permission_EditSupplierInformation {
            get {
                return ResourceManager.GetString("Permission_EditSupplierInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ResetPassword.
        /// </summary>
        internal static string Permission_ResetPassword {
            get {
                return ResourceManager.GetString("Permission_ResetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WarehouseMaterial.
        /// </summary>
        internal static string Permission_WarehouseMaterial {
            get {
                return ResourceManager.GetString("Permission_WarehouseMaterial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chức vụ: {0}.
        /// </summary>
        internal static string TaskManager_Label_Position {
            get {
                return ResourceManager.GetString("TaskManager_Label_Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Người dùng: {0}.
        /// </summary>
        internal static string TaskManager_Label_User {
            get {
                return ResourceManager.GetString("TaskManager_Label_User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap unlock {
            get {
                object obj = ResourceManager.GetObject("unlock", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap user_add {
            get {
                object obj = ResourceManager.GetObject("user_add", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap user_setting {
            get {
                object obj = ResourceManager.GetObject("user-setting", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
