//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BTL_LTTQ_QLKhoVLXD.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BTL_LTTQ_QLKhoVLXD.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _lock {
            get {
                object obj = ResourceManager.GetObject("lock", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ẩn mật khẩu.
        /// </summary>
        internal static string Checkbox_HidePassword {
            get {
                return ResourceManager.GetString("Checkbox_HidePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hiện mật khẩu.
        /// </summary>
        internal static string Checkbox_ShowPassword {
            get {
                return ResourceManager.GetString("Checkbox_ShowPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông báo.
        /// </summary>
        internal static string MessageBox_Caption_Notification {
            get {
                return ResourceManager.GetString("MessageBox_Caption_Notification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên đăng nhập đã tồn tại! Vui lòng chọn tên đăng nhập khác.
        /// </summary>
        internal static string MessageBox_Message_AccountExisted {
            get {
                return ResourceManager.GetString("MessageBox_Message_AccountExisted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản {0} không tồn tại!.
        /// </summary>
        internal static string MessageBox_Message_AccountNotExist {
            get {
                return ResourceManager.GetString("MessageBox_Message_AccountNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không thể đặt lại mật khẩu cho chính mình! Hãy sử dụng chức năng &quot;Thay đổi thông tin cá nhân&quot;.
        /// </summary>
        internal static string MessageBox_Message_CannotSelfResetPassword {
            get {
                return ResourceManager.GetString("MessageBox_Message_CannotSelfResetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thay đổi thành công!.
        /// </summary>
        internal static string MessageBox_Message_ChangeSuccessfully {
            get {
                return ResourceManager.GetString("MessageBox_Message_ChangeSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin của bạn sẽ được thay đổi. Vẫn tiếp tục?.
        /// </summary>
        internal static string MessageBox_Message_ConfirmChangeInfo {
            get {
                return ResourceManager.GetString("MessageBox_Message_ConfirmChangeInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu của bạn sẽ được thay đổi. Vẫn tiếp tục?.
        /// </summary>
        internal static string MessageBox_Message_ConfirmChangePassword {
            get {
                return ResourceManager.GetString("MessageBox_Message_ConfirmChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn có chắc chắn muốn thoát không?.
        /// </summary>
        internal static string MessageBox_Message_ConfirmExit {
            get {
                return ResourceManager.GetString("MessageBox_Message_ConfirmExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khảu của tài khoản {0} sẽ được thay đổi. Vẫn tiếp tục?.
        /// </summary>
        internal static string MessageBox_Message_ConfirmResetPassword {
            get {
                return ResourceManager.GetString("MessageBox_Message_ConfirmResetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tạo tài khoản thành công!.
        /// </summary>
        internal static string MessageBox_Message_CreateAccountSuccessfully {
            get {
                return ResourceManager.GetString("MessageBox_Message_CreateAccountSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khảu mới không được trùng mật khẩu cũ!.
        /// </summary>
        internal static string MessageBox_Message_DuplicatePassword {
            get {
                return ResourceManager.GetString("MessageBox_Message_DuplicatePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hãy nhập đầy đủ thông tin tài khoản!.
        /// </summary>
        internal static string MessageBox_Message_EnterFullAccountInfo {
            get {
                return ResourceManager.GetString("MessageBox_Message_EnterFullAccountInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hãy nhập đầy đủ thông tin cá nhân!.
        /// </summary>
        internal static string MessageBox_Message_EnterFullPersonalInfo {
            get {
                return ResourceManager.GetString("MessageBox_Message_EnterFullPersonalInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hãy nhập mật khẩu mới!.
        /// </summary>
        internal static string MessageBox_Message_EnterNewPassword {
            get {
                return ResourceManager.GetString("MessageBox_Message_EnterNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hãy nhập mật khẩu cũ!.
        /// </summary>
        internal static string MessageBox_Message_EnterOldPassword {
            get {
                return ResourceManager.GetString("MessageBox_Message_EnterOldPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hãy nhập mật khẩu!.
        /// </summary>
        internal static string MessageBox_Message_EnterPassword {
            get {
                return ResourceManager.GetString("MessageBox_Message_EnterPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hãy nhập tên đăng nhập.
        /// </summary>
        internal static string MessageBox_Message_EnterUsername {
            get {
                return ResourceManager.GetString("MessageBox_Message_EnterUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Định dạng họ tên không chính xác! Hãy thử lại.
        /// </summary>
        internal static string MessageBox_Message_InvalidNameFormat {
            get {
                return ResourceManager.GetString("MessageBox_Message_InvalidNameFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Định dạng số điện thoại không chính xác! Hãy thử lại.
        /// </summary>
        internal static string MessageBox_Message_InvalidPhoneNumberFormat {
            get {
                return ResourceManager.GetString("MessageBox_Message_InvalidPhoneNumberFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lỗi hệ thống! Hãy thử lại sau.
        /// </summary>
        internal static string MessageBox_Message_SystemError {
            get {
                return ResourceManager.GetString("MessageBox_Message_SystemError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sai tên tài khoản hoặc mật khẩu!.
        /// </summary>
        internal static string MessageBox_Message_WrongAccountInfo {
            get {
                return ResourceManager.GetString("MessageBox_Message_WrongAccountInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khảu cũ không chính xác!.
        /// </summary>
        internal static string MessageBox_Message_WrongOldPassword {
            get {
                return ResourceManager.GetString("MessageBox_Message_WrongOldPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vị trí: {0}.
        /// </summary>
        internal static string TaskManager_Label_Position {
            get {
                return ResourceManager.GetString("TaskManager_Label_Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Người dùng: {0}.
        /// </summary>
        internal static string TaskManager_Label_User {
            get {
                return ResourceManager.GetString("TaskManager_Label_User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap unlock {
            get {
                object obj = ResourceManager.GetObject("unlock", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap user_add {
            get {
                object obj = ResourceManager.GetObject("user_add", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap user_setting {
            get {
                object obj = ResourceManager.GetObject("user-setting", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
